using System.Collections.Generic;
using System.Linq;

using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

public static class ServiceRegistrationEmitter
{
    public static string Emit(List<ServiceRegistrationModel> models, string rootNamespace)
    {
        var option = Code.Create()
            .AppendLine("// <auto-generated/>","#nullable enable")
            .Using("Microsoft.Extensions.DependencyInjection")
            .Namespace(ns =>
            {
                ns.Name = rootNamespace;
                ns.Internal.Static.Class(cls => BuildServiceRegistrationClass(cls, models));
            });

        var body = option.Build();
        return body;
    }

    private static void BuildServiceRegistrationClass(TypeOption cls, List<ServiceRegistrationModel> models)
    {
        cls.WithName("ServiceRegistrationExtensions");

        cls.Internal.Method(m =>
        {
            m.WithName("AddAutoRegisteredServices")
             .WithReturnType("IServiceCollection")
             .WithParameters("this IServiceCollection services")
             .WithKeyword("static");

            foreach (var model in models)
            {
                var methodName = model.Lifetime switch
                {
                    ServiceLifetime.Transient => "AddTransient",
                    ServiceLifetime.Scoped => "AddScoped",
                    ServiceLifetime.Singleton => "AddSingleton",
                    _ => "AddTransient"
                };

                if (model.ServiceType is not null)
                    m.AppendLine($"services.{methodName}<{model.ServiceType}, {model.ImplementationType}>();");
                else
                    m.AppendLine($"services.{methodName}<{model.ImplementationType}>();");
            }

            m.AppendLine("return services;");
        });
    }
}
