using System.Collections.Generic;
using System.Linq;
using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 为每个 [SlashCommand] 方法生成 ICommandHandler 实现类 + AddSlashCommands() DI 注册扩展。
/// </summary>
public static class SlashCommandEmitter
{
    public static string Emit(string namespaceName, List<CommandMethodModel> commands)
    {
        var option = Code.Create()
            .AppendLines("// <auto-generated/>", "#nullable enable", "#pragma warning disable CS1998, CS8602, CS8604")
            .Using(
                "System",
                "System.Collections.Generic",
                "System.Threading",
                "System.Threading.Tasks",
                "ManInBlack.AI.Abstraction.Commands",
                "ManInBlack.AI.Abstraction.Middleware",
                "ManInBlack.AI.Commands",
                "Microsoft.Extensions.AI",
                "Microsoft.Extensions.DependencyInjection")
            .Namespace(ns =>
            {
                ns.Name = namespaceName;
                foreach (var c in commands)
                    BuildHandlerClass(ns, c);
                BuildServiceCollectionExtensions(ns, commands);
            });

        return option.Build();
    }

    private static void BuildHandlerClass(NamespaceOption ns, CommandMethodModel cmd)
    {
        var handlerClassName = GetHandlerClassName(cmd);

        ns.Public.Sealed.Class(cls =>
        {
            cls.WithName(handlerClassName);
            cls.Inherit("ICommandHandler");

            cls.AppendLine($"    public string CommandName => \"{Escape(cmd.CommandName)}\";");

            if (cmd.Aliases.Count > 0)
            {
                var aliasLiterals = string.Join(", ", cmd.Aliases.Select(a => $"\"{Escape(a)}\""));
                cls.AppendLine($"    public string[] Aliases => [{aliasLiterals}];");
            }
            else
            {
                cls.AppendLine("    public string[] Aliases => [];");
            }

            cls.AppendLine($"    public string Description => \"{Escape(cmd.Description)}\";");

            cls.Field(f =>
            {
                f.WithKeyword("private").WithKeyword("readonly")
                    .WithType("IServiceProvider").WithName("_serviceProvider");
            });

            cls.Constructor(ctor =>
            {
                ctor.WithKeyword("public").WithName(handlerClassName)
                    .WithParameter("IServiceProvider serviceProvider");
                ctor.AppendLine("_serviceProvider = serviceProvider;");
            });

            cls.Public.Method(m =>
            {
                m.WithName("ExecuteAsync")
                    .WithReturnType("IAsyncEnumerable<ChatResponseUpdate>")
                    .WithParameters("AgentContext context, ChatResponseUpdateHandler next, CancellationToken ct");

                m.AppendLine($"var instance = (_serviceProvider.GetService(typeof({cmd.ContainingTypeName})) as {cmd.ContainingTypeName})");
                m.AppendLine($"    ?? throw new System.InvalidOperationException(\"Failed to resolve type '{Escape(cmd.ContainingTypeShortName)}' from IServiceProvider.\");");
                m.AppendLine($"return instance.{cmd.MethodName}(context, next, ct);");
            });
        });
    }

    private static void BuildServiceCollectionExtensions(NamespaceOption ns, List<CommandMethodModel> commands)
    {
        ns.Internal.Static.Class(cls =>
        {
            cls.WithName("SlashCommandServiceExtensions");

            cls.Internal.Method(m =>
            {
                m.WithName("AddSlashCommands")
                    .WithReturnType("IServiceCollection")
                    .WithParameters("this IServiceCollection services")
                    .WithKeyword("static");

                foreach (var cmd in commands)
                    m.AppendLine($"services.AddScoped<ICommandHandler, {GetHandlerClassName(cmd)}>();");

                m.AppendLine("services.AddScoped<SlashCommandRegistry>();");   // Scoped:避免 captive dependency
                m.AppendLine("return services;");
            });
        });
    }

    private static string GetHandlerClassName(CommandMethodModel cmd)
    {
        var typeName = cmd.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        return $"{typeName}_{cmd.MethodName}_CommandHandler";
    }

    private static string Escape(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
}
