using System.Collections.Generic;
using System.Linq;
using System.Text;
using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 使用 EasyCodeBuilder 生成 per-tool handler + declaration 注册 + ToolExecutor + ToolRegistry
/// </summary>
public static class ToolCallerEmitter
{
    public static string Emit(string namespaceName, List<ToolMethodModel> tools)
    {
        var option = Code.Create()
            .AppendLines("// <auto-generated/>", "#nullable enable", "#pragma warning disable CS1998, CS8602, CS8604")
            .Using(
                "System",
                "System.Collections.Generic",
                "System.Collections.Concurrent",
                "System.Threading",
                "System.Threading.Tasks",
                "ManInBlack.AI.Abstraction.Tools",
                "ManInBlack.AI.Tools",
                "Microsoft.Extensions.AI",
                "Microsoft.Extensions.DependencyInjection")
            .Namespace(ns =>
            {
                ns.Name = namespaceName;

                // 为每个 [AiTool] 方法生成 handler 类
                foreach (var tool in tools)
                    BuildHandlerClass(ns, tool);

                // 生成 ToolExecutor（字典查找）
                BuildToolExecutorClass(ns);

                // 生成 AddToolHandlers() DI 注册扩展方法
                BuildServiceCollectionExtensions(ns, tools);
            });

        return option.Build();
    }

    private static void BuildHandlerClass(NamespaceOption ns, ToolMethodModel tool)
    {
        var handlerClassName = GetHandlerClassName(tool);

        ns.Public.Sealed.Class(cls =>
        {
            cls.WithName(handlerClassName);
            cls.Inherit("IToolHandler");

            // ToolName 属性
            cls.AppendLine($"    public string ToolName => \"{EscapeString(tool.ToolName)}\";");

            // IServiceProvider 字段
            cls.Field(f =>
            {
                f.WithKeyword("private").WithKeyword("readonly")
                    .WithType("IServiceProvider").WithName("_serviceProvider");
            });

            // 构造函数
            cls.Constructor(ctor =>
            {
                ctor.WithKeyword("public").WithName(handlerClassName)
                    .WithParameter("IServiceProvider serviceProvider");
                ctor.AppendLine("_serviceProvider = serviceProvider;");
            });

            // ExecuteAsync 方法
            cls.Public.Method(m =>
            {
                m.WithName("ExecuteAsync")
                    .WithReturnType("Task")
                    .WithParameters("ToolExecuteContext ctx, CancellationToken ct")
                    .WithKeyword("async");

                if (tool.FilterTypes.Count > 0)
                    m.AppendLine(BuildFilterPipelineLines(tool, "ctx"));
                else
                    m.AppendLine(BuildCoreInvocationLines(tool, "ctx"));
            });
        });
    }

    private static void BuildToolExecutorClass(NamespaceOption ns)
    {
        ns.Public.Sealed.Class(cls =>
        {
            cls.WithName("ToolExecutor");
            cls.Inherit("IToolExecutor");

            cls.Field(f =>
            {
                f.WithKeyword("private").WithKeyword("readonly")
                    .WithType("ConcurrentDictionary<string, IToolHandler>").WithName("_handlers");
            });

            cls.Constructor(ctor =>
            {
                ctor.WithKeyword("public").WithName("ToolExecutor")
                    .WithParameter("IEnumerable<IToolHandler> handlers");
                ctor.AppendLine("_handlers = new ConcurrentDictionary<string, IToolHandler>(handlers.ToDictionary(h => h.ToolName));");
            });

            cls.Public.Method(m =>
            {
                m.WithName("ExecuteAsync")
                    .WithReturnType("Task")
                    .WithParameters("ToolExecuteContext ctx, CancellationToken ct")
                    .WithKeyword("async");

                m.AppendLine("if (!_handlers.TryGetValue(ctx.ToolName, out var handler))");
                m.AppendLine("    throw new ArgumentException($\"Unknown tool: '{ctx.ToolName}'.\");");
                m.AppendLine("await handler.ExecuteAsync(ctx, ct);");
            });
        });
    }

    private static void BuildServiceCollectionExtensions(NamespaceOption ns, List<ToolMethodModel> tools)
    {
        ns.Internal.Static.Class(cls =>
        {
            cls.WithName("ToolHandlerServiceExtensions");

            cls.Internal.Method(m =>
            {
                m.WithName("AddToolHandlers")
                    .WithReturnType("IServiceCollection")
                    .WithParameters("this IServiceCollection services")
                    .WithKeyword("static");

                // 注册所有 handler
                foreach (var tool in tools)
                {
                    var handlerClassName = GetHandlerClassName(tool);
                    m.AppendLine($"services.AddScoped<IToolHandler, {handlerClassName}>();");
                }

                // 注册所有 declaration
                foreach (var tool in tools)
                {
                    var (toolName, group) = GetToolNameAndGroup(tool);
                    var declarationExpr = BuildDeclarationExpression(tool);
                    m.AppendLine($"services.AddSingleton<IToolDeclaration>(new ToolDeclaration(\"{EscapeString(toolName)}\", \"{EscapeString(group)}\", {declarationExpr}));");
                }

                // 注册 ToolRegistry 和 ToolExecutor
                m.AppendLine("services.AddSingleton<ToolRegistry>();");
                m.AppendLine("services.AddScoped<IToolExecutor, ToolExecutor>();");
                m.AppendLine("return services;");
            });
        });
    }

    private static string BuildDeclarationExpression(ToolMethodModel tool)
    {
        var jsonSchema = BuildParametersJsonSchema(tool);
        var returnSchema = BuildReturnJsonSchema(tool);
        var toolName = EscapeString(tool.ToolName);
        var summary = EscapeString(tool.Summary ?? "");
        var schemaVerbatim = EscapeVerbatimString(jsonSchema);

        if (returnSchema is not null)
        {
            var returnVerbatim = EscapeVerbatimString(returnSchema);
            return $"new ToolFunctionDeclaration(\"{toolName}\", \"{summary}\", @\"{schemaVerbatim}\", @\"{returnVerbatim}\")";
        }
        return $"new ToolFunctionDeclaration(\"{toolName}\", \"{summary}\", @\"{schemaVerbatim}\", null)";
    }

    private static (string toolName, string group) GetToolNameAndGroup(ToolMethodModel tool)
    {
        return (tool.ToolName, tool.ContainingTypeShortName.Split('.')[0]);
    }

    #region 参数提取 + 调用逻辑（与旧版本一致）

    private static string[] BuildFilterPipelineLines(ToolMethodModel tool, string ctxVar)
    {
        var lines = new List<string>();

        for (var i = 0; i < tool.FilterTypes.Count; i++)
        {
            var filterType = tool.FilterTypes[i];
            lines.Add($"var f{i} = ({filterType})_serviceProvider.GetRequiredService(typeof({filterType}));");
        }

        lines.Add("");

        lines.Add("System.Func<ToolExecuteContext, System.Threading.Tasks.Task> next = async ctx =>");
        lines.Add("{");
        foreach (var line in BuildCoreInvocationLines(tool, "ctx"))
            lines.Add("    " + line);
        lines.Add("};");

        for (var i = tool.FilterTypes.Count - 1; i >= 0; i--)
        {
            lines.Add($"var prev{i} = next;");
            lines.Add($"next = c => f{i}.ExecuteAsync(c, prev{i});");
        }

        lines.Add($"await next({ctxVar});");

        return lines.ToArray();
    }

    private static string[] BuildCoreInvocationLines(ToolMethodModel tool, string ctxVar)
    {
        var lines = new List<string>();

        foreach (var param in tool.Parameters)
            lines.AddRange(BuildParameterExtraction(param, tool.ToolName, ctxVar));

        if (!tool.IsStatic)
        {
            lines.Add($"var instance = (_serviceProvider.GetService(typeof({tool.ContainingTypeName})) as {tool.ContainingTypeName})");
            lines.Add($"    ?? throw new InvalidOperationException(\"Failed to resolve type '{tool.ContainingTypeShortName}' from IServiceProvider.\");");
        }

        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        var awaitPrefix = tool.IsAsync ? "await " : "";
        if (tool.IsStatic)
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"{awaitPrefix}{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = {awaitPrefix}{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
            }
        }
        else
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"{awaitPrefix}instance.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = {awaitPrefix}instance.{tool.MethodName}({argsList});");
            }
        }

        return lines.ToArray();
    }

    private static string[] BuildParameterExtraction(ToolParameterModel param, string toolName, string ctxVar)
    {
        var varName = $"{param.Name}_raw";
        var targetName = param.Name;
        var targetType = param.Type;

        if (param.HasDefaultValue)
        {
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                $"    : {param.DefaultValueExpr};"
            };
        }

        if (param.IsNullable)
        {
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                "    : null;"
            };
        }

        return new[]
        {
            $"if (!{ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) || {varName} is null)",
            $"    throw new ArgumentNullException(\"{param.Name}\", \"Required non-nullable parameter '{param.Name}' is missing or null for tool '{toolName}'.\");",
            $"var {targetName} = {ConvertExpr(varName, targetType, param)};"
        };
    }

    private static string ConvertExpr(string varName, string targetType, ToolParameterModel param)
    {
        if (targetType == "string" || targetType == "System.String")
            return $"{varName} as string ?? ({varName} is System.Text.Json.JsonElement {varName}_je ? {varName}_je.GetString() : {varName}?.ToString())";

        if (param.IsValueType)
        {
            var jeExtract = $"{varName} is System.Text.Json.JsonElement {varName}_je ? ({varName}_je.ValueKind == System.Text.Json.JsonValueKind.String ? {varName}_je.GetString() : {varName}_je.GetRawText()) : {varName}";
            var convertMethod = GetConvertMethod(targetType);
            if (!string.IsNullOrEmpty(convertMethod))
                return $"{varName} is {targetType} {varName}_v ? {varName}_v : {convertMethod}({jeExtract})";
            return $"{varName} is {targetType} {varName}_v ? {varName}_v : ({targetType})System.Convert.ChangeType({jeExtract}, typeof({targetType}))";
        }

        return $"{varName} as {targetType}";
    }

    private static string GetConvertMethod(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => "Convert.ToInt32",
            "long" or "System.Int64" => "Convert.ToInt64",
            "short" or "System.Int16" => "Convert.ToInt16",
            "byte" or "System.Byte" => "Convert.ToByte",
            "float" or "System.Single" => "Convert.ToSingle",
            "double" or "System.Double" => "Convert.ToDouble",
            "decimal" or "System.Decimal" => "Convert.ToDecimal",
            "bool" or "System.Boolean" => "Convert.ToBoolean",
            "char" or "System.Char" => "Convert.ToChar",
            "uint" or "System.UInt32" => "Convert.ToUInt32",
            "ulong" or "System.UInt64" => "Convert.ToUInt64",
            "ushort" or "System.UInt16" => "Convert.ToUInt16",
            "sbyte" or "System.SByte" => "Convert.ToSByte",
            "DateTime" or "System.DateTime" => "Convert.ToDateTime",
            _ => ""
        };
    }

    #endregion

    #region JSON Schema 生成（从 ToolDeclarationEmitter 迁移）

    private static string BuildParametersJsonSchema(ToolMethodModel tool)
    {
        var sb = new StringBuilder();
        sb.Append("{\"type\":\"object\",\"properties\":{");

        var firstProp = true;
        foreach (var param in tool.Parameters)
        {
            if (!firstProp) sb.Append(',');
            firstProp = false;

            sb.Append($"\"{EscapeJsonString(param.Name)}\":");
            sb.Append(BuildTypeSchemaJson(param.Type, param.IsNullable,
                tool.ParamDescriptions.TryGetValue(param.Name, out var desc) ? desc : null));
        }

        sb.Append('}');

        var requiredParams = tool.Parameters
            .Where(p => !p.IsNullable && !p.HasDefaultValue)
            .Select(p => p.Name)
            .ToList();

        if (requiredParams.Count > 0)
        {
            sb.Append(",\"required\":[");
            for (var i = 0; i < requiredParams.Count; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append($"\"{EscapeJsonString(requiredParams[i])}\"");
            }
            sb.Append(']');
        }

        sb.Append('}');
        return sb.ToString();
    }

    private static string? BuildReturnJsonSchema(ToolMethodModel tool)
    {
        if (tool.ReturnsVoid)
            return null;

        return BuildTypeSchemaJson(tool.ReturnType, false, tool.ReturnsDescription);
    }

    private static string BuildTypeSchemaJson(string type, bool isNullable, string? description)
    {
        var jsonType = MapToJsonSchemaType(type);
        var format = GetFormat(type);

        var sb = new StringBuilder();
        sb.Append('{');

        if (isNullable)
            sb.Append($"\"type\":[\"{jsonType}\",\"null\"]");
        else
            sb.Append($"\"type\":\"{jsonType}\"");

        if (format is not null)
            sb.Append($",\"format\":\"{format}\"");

        if (!string.IsNullOrWhiteSpace(description))
            sb.Append($",\"description\":\"{EscapeJsonString(description!)}\"");

        sb.Append('}');
        return sb.ToString();
    }

    private static string MapToJsonSchemaType(string type)
    {
        return type switch
        {
            "int" or "System.Int32" or "long" or "System.Int64" or "short" or "System.Int16"
            or "byte" or "System.Byte" or "sbyte" or "System.SByte" or "uint" or "System.UInt32"
            or "ulong" or "System.UInt64" or "ushort" or "System.UInt16" => "integer",
            "float" or "System.Single" or "double" or "System.Double" or "decimal" or "System.Decimal" => "number",
            "string" or "System.String" or "char" or "System.Char" or "System.DateTime" or "DateTime"
            or "System.DateTimeOffset" or "DateTimeOffset" => "string",
            "bool" or "System.Boolean" => "boolean",
            _ => "object"
        };
    }

    private static string? GetFormat(string type)
    {
        return type switch
        {
            "System.DateTime" or "DateTime" or "System.DateTimeOffset" or "DateTimeOffset" => "date-time",
            _ => null
        };
    }

    #endregion

    private static string GetHandlerClassName(ToolMethodModel tool)
    {
        var typeName = tool.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        return $"{typeName}_{tool.MethodName}_Handler";
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");

    private static string EscapeJsonString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");

    private static string EscapeVerbatimString(string s)
        => s.Replace("\"", "\"\"");
}
