using System.Collections.Generic;
using System.Linq;

using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 使用 EasyCodeBuilder 为包含 [AiTool] 方法的类生成 ToolInjection Middleware
/// </summary>
public static class ToolMiddlewareEmitter
{
    public static string Emit(string rootNamespace, List<ToolMiddlewareModel> models)
    {
        var option = Code.Create()
            .AppendLines("// <auto-generated/>", "#nullable enable")
            .Using(
                "System.Collections.Generic",
                "System.Runtime.CompilerServices",
                "System.Threading",
                "ManInBlack.AI.Abstraction.Middleware",
                "Microsoft.Extensions.AI",
                "Microsoft.Extensions.DependencyInjection")
            .Namespace(ns =>
            {
                ns.Name = rootNamespace;

                // 为每个工具类生成一个 Middleware
                foreach (var model in models)
                {
                    var capturedModel = model;
                    ns.Public.Class(cls => BuildMiddlewareClass(cls, capturedModel));
                }

                // 生成 DI 注册扩展方法
                ns.Internal.Static.Class(cls => BuildServiceExtensions(cls, models));
            });

        var body = option.Build();
        return body;
    }

    private static void BuildMiddlewareClass(TypeOption cls, ToolMiddlewareModel model)
    {
        var middlewareName = $"{model.ContainingTypeName}Middleware";
        var toolTypeRef = $"global::{model.FullyQualifiedTypeName}";

        cls.WithName(middlewareName);
        cls.Inherit("AgentMiddleware");

        cls.Public.Method(m =>
        {
            m.WithName("HandleAsync")
                .WithReturnType("IAsyncEnumerable<ChatResponseUpdate>")
                .WithParameters(
                    "AgentContext context, ChatResponseUpdateHandler next, [EnumeratorCancellation] CancellationToken ct = default")
                .WithKeyword("override")
                .WithKeyword("async");

            m.AppendLine($"var tools = {toolTypeRef}.AllToolDeclarations;");
            m.AppendLine("context.Options ??= new ChatOptions();");
            m.AppendLine("context.Options.Tools ??= [];");
            m.AppendLine("foreach (var tool in tools)");
            m.AppendLine("    context.Options.Tools!.Add(tool);");
            m.AppendLine("await foreach (var update in next().WithCancellation(ct))");
            m.AppendLine("    yield return update;");
        });
    }

    private static void BuildServiceExtensions(TypeOption cls, List<ToolMiddlewareModel> models)
    {
        cls.WithName("ToolMiddlewareServiceExtensions");

        cls.Internal.Method(m =>
        {
            m.WithName("AddToolMiddlewares")
                .WithReturnType("IServiceCollection")
                .WithParameters("this IServiceCollection services")
                .WithKeyword("static");

            foreach (var model in models)
            {
                var middlewareName = $"{model.ContainingTypeName}Middleware";
                m.AppendLine($"services.AddScoped<{middlewareName}>();");
            }

            m.AppendLine("return services;");
        });
    }
}
