using System.Collections.Generic;
using System.Linq;
using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 使用 EasyCodeBuilder 生成 ToolExecutor 类的源码
/// </summary>
public static class ToolCallerEmitter
{
    public static string Emit(string namespaceName, List<ToolMethodModel> tools)
    {
        var option = Code.Create()
            .AppendLines("// <auto-generated/>", "#nullable enable", "#pragma warning disable CS1998, CS8602, CS8604")
            .Using("System", "System.Collections.Generic", "System.Threading", "System.Threading.Tasks", "ManInBlack.AI.Abstraction.Tools", "Microsoft.Extensions.DependencyInjection")
            .Namespace(ns => {
                ns.Name = namespaceName;
                ns.Public.Class(cls => BuildToolExecutorClass(cls, tools));
                ns.Public.Static.Class(cls => BuildServiceCollectionExtensions(cls));
            });

        var body = option.Build();
        return body;
    }

    private static void BuildToolExecutorClass(TypeOption cls, List<ToolMethodModel> tools)
    {
        cls.WithName("ToolExecutor");

        // 实现 IToolExecutor 接口
        cls.Inherit("IToolExecutor");

        // 字段：private readonly IServiceProvider _serviceProvider;
        cls.Field(f => {
            f.WithKeyword("private").WithKeyword("readonly")
                .WithType("IServiceProvider").WithName("_serviceProvider");
        });

        // 构造函数：public ToolExecutor(IServiceProvider serviceProvider)
        cls.Constructor(ctor => {
            ctor.WithKeyword("public").WithName("ToolExecutor")
                .WithParameter("IServiceProvider serviceProvider");
            ctor.AppendLine("_serviceProvider = serviceProvider;");
        });

        // ExecuteAsync 方法（实现 IToolExecutor）
        BuildExecuteAsyncMethod(cls, tools);

        // 每个 tool 的辅助方法
        foreach (var tool in tools)
            BuildToolHelperMethod(cls, tool);
    }

    /// <summary>
    /// 生成 AddToolExecutor() 扩展方法，将 ToolExecutor 注册到 DI 容器
    /// </summary>
    private static void BuildServiceCollectionExtensions(TypeOption cls)
    {
        cls.WithName("ToolExecutorServiceExtensions");

        cls.Public.Method(m => {
            m.WithName("AddToolExecutor")
                .WithReturnType("IServiceCollection")
                .WithParameters("this IServiceCollection services")
                .WithKeyword("static")
                .AppendLine("services.AddScoped<IToolExecutor, ToolExecutor>();")
                .AppendLine("return services;");
        });
    }

    private static void BuildExecuteAsyncMethod(TypeOption cls, List<ToolMethodModel> tools)
    {
        cls.Public.Method(m => {
            m.WithName("ExecuteAsync")
                .WithReturnType("Task")
                .WithParameters("ToolExecuteContext ctx, CancellationToken ct")
                .WithKeyword("async");

            // try-catch 包裹，异常写入 ctx.Error
            m.AppendLine("try", "{");

            m.Switch(sw => {
                sw.WithExpression("ctx.ToolName");

                foreach (var tool in tools)
                {
                    var helperName = GetHelperMethodName(tool);
                    sw.Case(c => {
                        c.Value = $"\"{tool.ToolName}\"";
                        c.AppendLine($"await {helperName}(ctx);", "break;");
                    });
                }

                sw.Default(d => {
                    d.AppendLine("throw new ArgumentException($\"Unknown tool: '{ctx.ToolName}'.\");");
                });
            });

            m.AppendLine("}", "catch (Exception ex)", "{", "    ctx.Error = ex;", "}");
        });
    }

    private static void BuildToolHelperMethod(TypeOption cls, ToolMethodModel tool)
    {
        var helperName = GetHelperMethodName(tool);

        cls.Method(m => {
            m.WithName(helperName)
                .WithReturnType("Task")
                .WithParameters("ToolExecuteContext context")
                .WithKeyword("private")
                .WithKeyword("async");

            if (tool.FilterTypes.Count > 0)
                m.AppendLine(BuildFilterPipelineLines(tool));
            else
                m.AppendLine(BuildCoreInvocationLines(tool, "context"));
        });
    }

    private static string[] BuildFilterPipelineLines(ToolMethodModel tool)
    {
        var lines = new List<string>();

        // 声明 filter 变量，从 DI 获取或 new
        for (var i = 0; i < tool.FilterTypes.Count; i++)
        {
            var filterType = tool.FilterTypes[i];
            lines.Add($"var f{i} = ({filterType})_serviceProvider.GetRequiredService(typeof({filterType}));");
        }

        lines.Add("");

        // 核心调用作为最内层委托
        lines.Add("System.Func<ManInBlack.AI.Abstraction.Tools.ToolExecuteContext, System.Threading.Tasks.Task> next = async ctx =>");
        lines.Add("{");
        foreach (var line in BuildCoreInvocationLines(tool, "ctx"))
            lines.Add("    " + line);
        lines.Add("};");

        // 反向包裹 filter（从后往前）
        for (var i = tool.FilterTypes.Count - 1; i >= 0; i--)
        {
            lines.Add($"var prev{i} = next;");
            lines.Add($"next = c => f{i}.ExecuteAsync(c, prev{i});");
        }

        lines.Add("await next(context);");

        return lines.ToArray();
    }

    private static string[] BuildCoreInvocationLines(ToolMethodModel tool, string ctxVar)
    {
        var lines = new List<string>();

        // 参数解析
        foreach (var param in tool.Parameters)
            lines.AddRange(BuildParameterExtraction(param, tool.ToolName, ctxVar));

        // 从 IServiceProvider 获取实例（非静态方法）
        if (!tool.IsStatic)
        {
            lines.Add($"var instance = (_serviceProvider.GetService(typeof({tool.ContainingTypeName})) as {tool.ContainingTypeName})");
            lines.Add($"    ?? throw new InvalidOperationException(\"Failed to resolve type '{tool.ContainingTypeShortName}' from IServiceProvider.\");");
        }

        // 调用方法并设置 Result
        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        var awaitPrefix = tool.IsAsync ? "await " : "";
        if (tool.IsStatic)
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"{awaitPrefix}{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = {awaitPrefix}{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
            }
        }
        else
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"{awaitPrefix}instance.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = {awaitPrefix}instance.{tool.MethodName}({argsList});");
            }
        }

        return lines.ToArray();
    }

    private static string[] BuildParameterExtraction(ToolParameterModel param, string toolName, string ctxVar)
    {
        var varName    = $"{param.Name}_raw";
        var targetName = param.Name;
        var targetType = param.Type;

        if (param.HasDefaultValue)
        {
            // 有默认值的参数：缺失时用默认值
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                $"    : {param.DefaultValueExpr};"
            };
        }

        if (param.IsNullable)
        {
            // nullable + 无默认值
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                "    : null;"
            };
        }

        // 必填参数：缺失或 null 时抛异常
        return new[]
        {
            $"if (!{ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) || {varName} is null)",
            $"    throw new ArgumentNullException(\"{param.Name}\", \"Required non-nullable parameter '{param.Name}' is missing or null for tool '{toolName}'.\");",
            $"var {targetName} = {ConvertExpr(varName, targetType, param)};"
        };
    }

    /// <summary>
    /// 生成类型转换表达式（所有类型名使用全称）
    /// </summary>
    private static string ConvertExpr(string varName, string targetType, ToolParameterModel param)
    {
        // string 类型：优先 as 转换，JsonElement 用 GetString()
        if (targetType == "string" || targetType == "System.String")
            return $"{varName} as string ?? ({varName} is System.Text.Json.JsonElement {varName}_je ? {varName}_je.GetString() : {varName}?.ToString())";

        // 值类型：先检查是否已装箱为正确类型，再处理 JsonElement（支持 Number 和 String 类型），最后用 Convert
        if (param.IsValueType)
        {
            // 从 JsonElement 提取文本：String 类型用 GetString()，Number 等类型用 GetRawText()
            var jeExtract = $"{varName} is System.Text.Json.JsonElement {varName}_je ? ({varName}_je.ValueKind == System.Text.Json.JsonValueKind.String ? {varName}_je.GetString() : {varName}_je.GetRawText()) : {varName}";
            var convertMethod = GetConvertMethod(targetType);
            if (!string.IsNullOrEmpty(convertMethod))
                return $"{varName} is {targetType} {varName}_v ? {varName}_v : {convertMethod}({jeExtract})";
            // 未知值类型，使用 ChangeType 并传入 typeof
            return $"{varName} is {targetType} {varName}_v ? {varName}_v : ({targetType})System.Convert.ChangeType({jeExtract}, typeof({targetType}))";
        }

        // 引用类型：直接 as 转换
        return $"{varName} as {targetType}";
    }

    private static string GetConvertMethod(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => "Convert.ToInt32",
            "long" or "System.Int64" => "Convert.ToInt64",
            "short" or "System.Int16" => "Convert.ToInt16",
            "byte" or "System.Byte" => "Convert.ToByte",
            "float" or "System.Single" => "Convert.ToSingle",
            "double" or "System.Double" => "Convert.ToDouble",
            "decimal" or "System.Decimal" => "Convert.ToDecimal",
            "bool" or "System.Boolean" => "Convert.ToBoolean",
            "char" or "System.Char" => "Convert.ToChar",
            "uint" or "System.UInt32" => "Convert.ToUInt32",
            "ulong" or "System.UInt64" => "Convert.ToUInt64",
            "ushort" or "System.UInt16" => "Convert.ToUInt16",
            "sbyte" or "System.SByte" => "Convert.ToSByte",
            "DateTime" or "System.DateTime" => "Convert.ToDateTime",
            _ => ""// fallback: 使用 ChangeType
        };
    }

    private static string GetHelperMethodName(ToolMethodModel tool)
    {
        // 用类名和方法名组合，避免特殊字符
        var typeName   = tool.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        var methodName = tool.MethodName;
        return $"Call_{typeName}_{methodName}";
    }
}