using System.Collections.Generic;
using System.Linq;

using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

public static class ServiceRegistrationEmitter
{
    public static string Emit(List<ServiceRegistrationModel> models)
    {
        var option = Code.Create()
            .Using(new[] { "Microsoft.Extensions.DependencyInjection" })
            .Namespace(ns =>
            {
                ns.Name = "Microsoft.Extensions.DependencyInjection";
                ns.Public.Static.Class(cls => BuildServiceRegistrationClass(cls, models));
            });

        var body = Code.Build(option, new CodeBuilder());
        return "// <auto-generated/>\n#nullable enable\n" + body;
    }

    private static void BuildServiceRegistrationClass(TypeOption cls, List<ServiceRegistrationModel> models)
    {
        cls.WithName("ServiceRegistrationExtensions");

        cls.Public.Method(m =>
        {
            m.WithName("AddAutoRegisteredServices")
             .WithReturnType("IServiceCollection")
             .WithParameters("this IServiceCollection services")
             .WithKeyword("static");

            foreach (var model in models)
            {
                var methodName = model.Lifetime switch
                {
                    ServiceLifetime.Transient => "AddTransient",
                    ServiceLifetime.Scoped => "AddScoped",
                    ServiceLifetime.Singleton => "AddSingleton",
                    _ => "AddTransient"
                };

                if (model.ServiceType is not null)
                    Code.AppendLine(m, new[] { $"services.{methodName}<{model.ServiceType}, {model.ImplementationType}>();" });
                else
                    Code.AppendLine(m, new[] { $"services.{methodName}<{model.ImplementationType}>();" });
            }

            Code.AppendLine(m, new[] { "return services;" });
        });
    }
}
