using System.Collections.Generic;
using System.Text;

namespace ManInBlack.AI.SourceGenerator;

public static class ServiceRegistrationEmitter
{
    public static string Emit(List<ServiceRegistrationModel> models)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class ServiceRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddAutoRegisteredServices(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var model in models)
        {
            var methodName = model.Lifetime switch
            {
                ServiceLifetime.Transient => "AddTransient",
                ServiceLifetime.Scoped => "AddScoped",
                ServiceLifetime.Singleton => "AddSingleton",
                _ => "AddTransient"
            };

            if (model.ServiceType is not null)
            {
                sb.AppendLine($"        services.{methodName}<{model.ServiceType}, {model.ImplementationType}>();");
            }
            else
            {
                sb.AppendLine($"        services.{methodName}<{model.ImplementationType}>();");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
