using System.Collections.Generic;
using System.Linq;

using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 使用 EasyCodeBuilder 生成 ToolCaller 类的源码
/// </summary>
public static class ToolCallerEmitter
{
    public static string Emit(string namespaceName, List<ToolMethodModel> tools)
    {
        var option = Code.Create()
            .Using(new[]
            {
                "System",
                "System.Collections.Generic",
                "System.Threading.Tasks",
                "ManInBlack.AI.Tools",
                "Microsoft.Extensions.DependencyInjection"
            })
            .Namespace(ns =>
            {
                ns.Name = namespaceName;
                ns.Public.Class(cls => BuildToolCallerClass(cls, tools));
            });

        var body = Code.Build(option, new CodeBuilder());
        return "// <auto-generated/>\n#nullable enable\n#pragma warning disable CS1998\n" + body;
    }

    private static void BuildToolCallerClass(TypeOption cls, List<ToolMethodModel> tools)
    {
        cls.WithName("ToolCaller");

        // 字段：private readonly IServiceProvider _serviceProvider;
        cls.Field(f =>
        {
            f.WithKeyword("private").WithKeyword("readonly")
             .WithType("IServiceProvider").WithName("_serviceProvider");
        });

        // 构造函数：public ToolCaller(IServiceProvider serviceProvider)
        cls.Constructor(ctor =>
        {
            ctor.WithKeyword("public").WithName("ToolCaller")
                .WithParameter("IServiceProvider serviceProvider");
            Code.AppendLine(ctor, new[] { "_serviceProvider = serviceProvider;" });
        });

        // CallTool 方法
        BuildCallToolMethod(cls, tools);

        // 每个 tool 的辅助方法
        foreach (var tool in tools)
            BuildToolHelperMethod(cls, tool);
    }

    private static void BuildCallToolMethod(TypeOption cls, List<ToolMethodModel> tools)
    {
        cls.Public.Method(m =>
        {
            m.WithName("CallTool")
             .WithReturnType("Task")
             .WithParameters("ToolExecuteContext context")
             .WithKeyword("async");

            m.Switch(sw =>
            {
                sw.WithExpression("context.ToolName");

                foreach (var tool in tools)
                {
                    var helperName = GetHelperMethodName(tool);
                    sw.Case(c =>
                    {
                        c.Value = $"\"{tool.ToolName}\"";
                        Code.AppendLine(c, new[] { $"await {helperName}(context);", "break;" });
                    });
                }

                sw.Default(d =>
                {
                    Code.AppendLine(d, new[] { "throw new ArgumentException($\"Unknown tool: '{context.ToolName}'.\");" });
                });
            });
        });
    }

    private static void BuildToolHelperMethod(TypeOption cls, ToolMethodModel tool)
    {
        var helperName = GetHelperMethodName(tool);

        cls.Method(m =>
        {
            m.WithName(helperName)
             .WithReturnType("Task")
             .WithParameters("ToolExecuteContext context")
             .WithKeyword("private")
             .WithKeyword("async");

            if (tool.FilterTypes.Count > 0)
                Code.AppendLine(m, BuildFilterPipelineLines(tool));
            else
                Code.AppendLine(m, BuildCoreInvocationLines(tool, "context"));
        });
    }

    private static string[] BuildFilterPipelineLines(ToolMethodModel tool)
    {
        var lines = new List<string>();

        // 声明 filter 变量，从 DI 获取或 new
        for (var i = 0; i < tool.FilterTypes.Count; i++)
        {
            var filterType = tool.FilterTypes[i];
            lines.Add($"var f{i} = ({filterType})_serviceProvider.GetRequiredService(typeof({filterType}));");
        }

        lines.Add("");

        // 核心调用作为最内层委托
        lines.Add("System.Func<ManInBlack.AI.Tools.ToolExecuteContext, System.Threading.Tasks.Task> next = async ctx =>");
        lines.Add("{");
        foreach (var line in BuildCoreInvocationLines(tool, "ctx"))
            lines.Add("    " + line);
        lines.Add("};");

        // 反向包裹 filter（从后往前）
        for (var i = tool.FilterTypes.Count - 1; i >= 0; i--)
        {
            lines.Add($"var prev{i} = next;");
            lines.Add($"next = c => f{i}.ExecuteAsync(c, prev{i});");
        }

        lines.Add("await next(context);");

        return lines.ToArray();
    }

    private static string[] BuildCoreInvocationLines(ToolMethodModel tool, string ctxVar)
    {
        var lines = new List<string>();

        // 参数解析
        foreach (var param in tool.Parameters)
            lines.AddRange(BuildParameterExtraction(param, tool.ToolName, ctxVar));

        // 从 IServiceProvider 获取实例（非静态方法）
        if (!tool.IsStatic)
        {
            lines.Add($"var instance = (_serviceProvider.GetService(typeof({tool.ContainingTypeName})) as {tool.ContainingTypeName})");
            lines.Add($"    ?? throw new InvalidOperationException(\"Failed to resolve type '{tool.ContainingTypeShortName}' from IServiceProvider.\");");
        }

        // 调用方法并设置 Result
        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        if (tool.IsStatic)
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = {tool.ContainingTypeName}.{tool.MethodName}({argsList});");
            }
        }
        else
        {
            if (tool.ReturnsVoid)
            {
                lines.Add($"instance.{tool.MethodName}({argsList});");
                lines.Add($"{ctxVar}.Result = null;");
            }
            else
            {
                lines.Add($"{ctxVar}.Result = instance.{tool.MethodName}({argsList});");
            }
        }

        return lines.ToArray();
    }

    private static string[] BuildParameterExtraction(ToolParameterModel param, string toolName, string ctxVar)
    {
        var varName = $"{param.Name}_raw";
        var targetName = param.Name;
        var targetType = param.Type;

        if (param.HasDefaultValue)
        {
            // 有默认值的参数：缺失时用默认值
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                $"    : {param.DefaultValueExpr};"
            };
        }

        if (param.IsNullable)
        {
            // nullable + 无默认值
            return new[]
            {
                $"var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null",
                $"    ? {ConvertExpr(varName, targetType, param)}",
                "    : null;"
            };
        }

        // 必填参数：缺失或 null 时抛异常
        return new[]
        {
            $"if (!{ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) || {varName} is null)",
            $"    throw new ArgumentNullException(\"{param.Name}\", \"Required non-nullable parameter '{param.Name}' is missing or null for tool '{toolName}'.\");",
            $"var {targetName} = {ConvertExpr(varName, targetType, param)};"
        };
    }

    /// <summary>
    /// 生成类型转换表达式（所有类型名使用全称）
    /// </summary>
    private static string ConvertExpr(string varName, string targetType, ToolParameterModel param)
    {
        // string 类型直接 as 转换
        if (targetType == "string" || targetType == "System.String")
            return $"{varName} as string ?? {varName}?.ToString()";

        // bool 特殊处理
        if (targetType == "bool" || targetType == "System.Boolean")
            return $"{varName} is bool {varName}_b ? {varName}_b : Convert.ToBoolean({varName})";

        // 常见值类型：先检查是否已装箱为正确类型，否则用 Convert
        if (param.IsValueType)
        {
            var convertMethod = GetConvertMethod(targetType);
            if (!string.IsNullOrEmpty(convertMethod))
                return $"{varName} is {targetType} {varName}_v ? {varName}_v : {convertMethod}({varName})";
            // 未知值类型，使用 ChangeType 并传入 typeof
            return $"{varName} is {targetType} {varName}_v ? {varName}_v : ({targetType})System.Convert.ChangeType({varName}, typeof({targetType}))";
        }

        // 引用类型：直接 as 转换
        return $"{varName} as {targetType}";
    }

    private static string GetConvertMethod(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => "Convert.ToInt32",
            "long" or "System.Int64" => "Convert.ToInt64",
            "short" or "System.Int16" => "Convert.ToInt16",
            "byte" or "System.Byte" => "Convert.ToByte",
            "float" or "System.Single" => "Convert.ToSingle",
            "double" or "System.Double" => "Convert.ToDouble",
            "decimal" or "System.Decimal" => "Convert.ToDecimal",
            "bool" or "System.Boolean" => "Convert.ToBoolean",
            "char" or "System.Char" => "Convert.ToChar",
            "uint" or "System.UInt32" => "Convert.ToUInt32",
            "ulong" or "System.UInt64" => "Convert.ToUInt64",
            "ushort" or "System.UInt16" => "Convert.ToUInt16",
            "sbyte" or "System.SByte" => "Convert.ToSByte",
            "DateTime" or "System.DateTime" => "Convert.ToDateTime",
            _ => "" // fallback: 使用 ChangeType
        };
    }

    private static string GetHelperMethodName(ToolMethodModel tool)
    {
        // 用类名和方法名组合，避免特殊字符
        var typeName = tool.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        var methodName = tool.MethodName;
        return $"Call_{typeName}_{methodName}";
    }
}
