using System.Collections.Generic;
using System.Linq;
using System.Text;

using Fengb3.EasyCodeBuilder;
using Fengb3.EasyCodeBuilder.Csharp;
using Fengb3.EasyCodeBuilder.Csharp.OptionConfigurations;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 使用 EasyCodeBuilder 为包含 [AiTool] 方法的类型生成 partial 类，包含 AIFunctionDeclaration 静态成员
/// </summary>
public static class ToolDeclarationEmitter
{
    public static string Emit(string namespaceName, string typeName, List<ToolDeclarationModel> tools)
    {
        var option = Code.Create()
            .Using("Microsoft.Extensions.AI")
            .Namespace(ns =>
            {
                ns.Name = namespaceName;
                BuildPartialClass(ns, typeName, tools);
            });

        var body = Code.Build(option, new CodeBuilder());
        return "// <auto-generated/>\n#nullable enable\n" + body;
    }

    private static void BuildPartialClass(NamespaceOption ns, string typeName, List<ToolDeclarationModel> tools)
    {
        var parts = typeName.Split('.');

        if (parts.Length == 1)
        {
            ns.Class(cls =>
            {
                cls.WithName(parts[0]);
                cls.Keywords.Add("partial");
                BuildDeclarationMembers(cls, tools);
            });
        }
        else
        {
            // 嵌套类型：递归包裹 partial 类
            ns.Class(cls =>
            {
                cls.WithName(parts[0]);
                cls.Keywords.Add("partial");
                BuildNestedClass(cls, parts, 1, tools);
            });
        }
    }

    private static void BuildNestedClass(TypeOption parent, string[] parts, int index, List<ToolDeclarationModel> tools)
    {
        if (index == parts.Length - 1)
        {
            parent.NestedClass(cls =>
            {
                cls.WithName(parts[index]);
                cls.Keywords.Add("partial");
                BuildDeclarationMembers(cls, tools);
            });
        }
        else
        {
            parent.NestedClass(cls =>
            {
                cls.WithName(parts[index]);
                cls.Keywords.Add("partial");
                BuildNestedClass(cls, parts, index + 1, tools);
            });
        }
    }

    private static void BuildDeclarationMembers(TypeOption cls, List<ToolDeclarationModel> tools)
    {
        // 为每个方法生成静态只读 ToolFunctionDeclaration 字段
        foreach (var tool in tools)
        {
            var fieldName = $"{tool.MethodName}_ToolDecl";
            var jsonSchema = BuildParametersJsonSchema(tool);
            var returnSchema = BuildReturnJsonSchema(tool);
            var toolName = EscapeString(tool.ToolName);
            var summary = EscapeString(tool.Summary ?? "");
            var schemaVerbatim = EscapeVerbatimString(jsonSchema);

            cls.Public.Static.Field(f =>
            {
                f.WithKeyword("readonly")
                    .WithType("global::ManInBlack.AI.Tools.ToolFunctionDeclaration")
                    .WithName(fieldName);

                if (returnSchema is not null)
                {
                    var returnVerbatim = EscapeVerbatimString(returnSchema);
                    f.WithInitializer(
                        $"new(\"{toolName}\", \"{summary}\", @\"{schemaVerbatim}\", @\"{returnVerbatim}\")");
                }
                else
                {
                    f.WithInitializer(
                        $"new(\"{toolName}\", \"{summary}\", @\"{schemaVerbatim}\", null)");
                }
            });
        }

        // 生成 AllToolDeclarations 静态数组
        cls.Public.Static.Field(f =>
        {
            f.WithKeyword("readonly")
                .WithType("global::Microsoft.Extensions.AI.AIFunctionDeclaration[]")
                .WithName("AllToolDeclarations");

            var elements = string.Join(", ", tools.Select(t => $"{t.MethodName}_ToolDecl"));
            f.WithInitializer($"{{ {elements} }}");
        });
    }

    /// <summary>
    /// 构建参数的 JSON Schema
    /// </summary>
    private static string BuildParametersJsonSchema(ToolDeclarationModel tool)
    {
        var sb = new StringBuilder();
        sb.Append("{\"type\":\"object\",\"properties\":{");

        var firstProp = true;
        foreach (var param in tool.Parameters)
        {
            if (!firstProp) sb.Append(',');
            firstProp = false;

            sb.Append($"\"{EscapeJsonString(param.Name)}\":");
            sb.Append(BuildTypeSchemaJson(param.Type, param.IsNullable,
                tool.ParamDescriptions.TryGetValue(param.Name, out var desc) ? desc : null));
        }

        sb.Append("}");

        var requiredParams = tool.Parameters
            .Where(p => !p.IsNullable && !p.HasDefaultValue)
            .Select(p => p.Name)
            .ToList();

        if (requiredParams.Count > 0)
        {
            sb.Append(",\"required\":[");
            for (var i = 0; i < requiredParams.Count; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append($"\"{EscapeJsonString(requiredParams[i])}\"");
            }
            sb.Append(']');
        }

        sb.Append('}');
        return sb.ToString();
    }

    /// <summary>
    /// 构建返回值的 JSON Schema
    /// </summary>
    private static string? BuildReturnJsonSchema(ToolDeclarationModel tool)
    {
        if (tool.ReturnsVoid)
            return null;

        return BuildTypeSchemaJson(tool.ReturnType, false, tool.ReturnsDescription);
    }

    /// <summary>
    /// 构建 JSON Schema 类型描述片段
    /// </summary>
    private static string BuildTypeSchemaJson(string type, bool isNullable, string? description)
    {
        var jsonType = MapToJsonSchemaType(type);
        var format = GetFormat(type);

        var sb = new StringBuilder();
        sb.Append('{');

        if (isNullable)
            sb.Append($"\"type\":[\"{jsonType}\",\"null\"]");
        else
            sb.Append($"\"type\":\"{jsonType}\"");

        if (format is not null)
            sb.Append($",\"format\":\"{format}\"");

        if (!string.IsNullOrWhiteSpace(description))
            sb.Append($",\"description\":\"{EscapeJsonString(description!)}\"");

        sb.Append('}');
        return sb.ToString();
    }

    private static string MapToJsonSchemaType(string type)
    {
        switch (type)
        {
            case "int":
            case "System.Int32":
            case "long":
            case "System.Int64":
            case "short":
            case "System.Int16":
            case "byte":
            case "System.Byte":
            case "sbyte":
            case "System.SByte":
            case "uint":
            case "System.UInt32":
            case "ulong":
            case "System.UInt64":
            case "ushort":
            case "System.UInt16":
                return "integer";
            case "float":
            case "System.Single":
            case "double":
            case "System.Double":
            case "decimal":
            case "System.Decimal":
                return "number";
            case "string":
            case "System.String":
            case "char":
            case "System.Char":
            case "System.DateTime":
            case "DateTime":
            case "System.DateTimeOffset":
            case "DateTimeOffset":
                return "string";
            case "bool":
            case "System.Boolean":
                return "boolean";
            default:
                return "object";
        }
    }

    private static string? GetFormat(string type)
    {
        switch (type)
        {
            case "System.DateTime":
            case "DateTime":
            case "System.DateTimeOffset":
            case "DateTimeOffset":
                return "date-time";
            default:
                return null;
        }
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }

    private static string EscapeJsonString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }

    private static string EscapeVerbatimString(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
