using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 生成 ToolCaller 类的源码
/// </summary>
public static class ToolCallerEmitter
{
    public static string Emit(string namespaceName, List<ToolMethodModel> tools)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("public class ToolCaller");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public ToolCaller(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CallTool 方法
        EmitCallToolMethod(sb, tools);
        sb.AppendLine();

        // 每个 tool 方法的辅助方法
        foreach (var tool in tools)
        {
            EmitToolHelperMethod(sb, tool);
            sb.AppendLine();
        }

        // 移除最后一个多余空行
        if (sb.Length >= 2 && sb[sb.Length - 1] == '\n' && sb[sb.Length - 2] == '\n')
            sb.Length--;

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitCallToolMethod(StringBuilder sb, List<ToolMethodModel> tools)
    {
        sb.AppendLine("    public object? CallTool(string name, Dictionary<string, object?> arguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        return name switch");
        sb.AppendLine("        {");

        foreach (var tool in tools)
        {
            var helperName = GetHelperMethodName(tool);
            sb.AppendLine($"            \"{tool.ToolName}\" => {helperName}(arguments),");
        }

        sb.AppendLine("            _ => throw new ArgumentException($\"Unknown tool: '{name}'.\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitToolHelperMethod(StringBuilder sb, ToolMethodModel tool)
    {
        var helperName = GetHelperMethodName(tool);
        sb.AppendLine($"    private object? {helperName}(Dictionary<string, object?> arguments)");
        sb.AppendLine("    {");

        // 参数解析
        foreach (var param in tool.Parameters)
        {
            EmitParameterExtraction(sb, param, tool.ToolName);
        }

        // 从 IServiceProvider 获取实例（非静态方法）
        if (!tool.IsStatic)
        {
            sb.AppendLine($"        var instance = (_serviceProvider.GetService(typeof({tool.ContainingTypeName})) as {tool.ContainingTypeName})");
            sb.AppendLine($"            ?? throw new InvalidOperationException(\"Failed to resolve type '{tool.ContainingTypeShortName}' from IServiceProvider.\");");
        }

        // 调用方法
        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        if (tool.IsStatic)
        {
            if (tool.ReturnsVoid)
            {
                sb.AppendLine($"        {tool.ContainingTypeName}.{tool.MethodName}({argsList});");
                sb.AppendLine("        return null;");
            }
            else
            {
                sb.AppendLine($"        return {tool.ContainingTypeName}.{tool.MethodName}({argsList});");
            }
        }
        else
        {
            if (tool.ReturnsVoid)
            {
                sb.AppendLine($"        instance.{tool.MethodName}({argsList});");
                sb.AppendLine("        return null;");
            }
            else
            {
                sb.AppendLine($"        return instance.{tool.MethodName}({argsList});");
            }
        }

        sb.AppendLine("    }");
    }

    private static void EmitParameterExtraction(StringBuilder sb, ToolParameterModel param, string toolName)
    {
        var varName = $"{param.Name}_raw";
        var targetName = param.Name;
        var targetType = param.Type;

        if (param.HasDefaultValue)
        {
            // 有默认值的参数：缺失时用默认值
            if (param.IsNullable)
            {
                // nullable + 有默认值
                sb.AppendLine($"        var {targetName} = arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
                sb.AppendLine($"            ? {ConvertExpr(varName, targetType, param)}");
                sb.AppendLine($"            : {param.DefaultValueExpr};");
            }
            else
            {
                // 非nullable + 有默认值：null 也用默认值
                sb.AppendLine($"        var {targetName} = arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
                sb.AppendLine($"            ? {ConvertExpr(varName, targetType, param)}");
                sb.AppendLine($"            : {param.DefaultValueExpr};");
            }
        }
        else if (param.IsNullable)
        {
            // nullable + 无默认值
            sb.AppendLine($"        var {targetName} = arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
            sb.AppendLine($"            ? {ConvertExpr(varName, targetType, param)}");
            sb.AppendLine($"            : null;");
        }
        else
        {
            // 必填参数：缺失或 null 时抛异常
            sb.AppendLine($"        if (!arguments.TryGetValue(\"{param.Name}\", out var {varName}) || {varName} is null)");
            sb.AppendLine($"            throw new ArgumentNullException(\"{param.Name}\", \"Required non-nullable parameter '{param.Name}' is missing or null for tool '{toolName}'.\");");
            sb.AppendLine($"        var {targetName} = {ConvertExpr(varName, targetType, param)};");
        }
    }

    /// <summary>
    /// 生成类型转换表达式（所有类型名使用全称）
    /// </summary>
    private static string ConvertExpr(string varName, string targetType, ToolParameterModel param)
    {
        // string 类型直接 as 转换
        if (targetType == "string" || targetType == "System.String")
            return $"{varName} as string ?? {varName}?.ToString()";

        // bool 特殊处理
        if (targetType == "bool" || targetType == "System.Boolean")
            return $"{varName} is bool {varName}_b ? {varName}_b : Convert.ToBoolean({varName})";

        // 常见值类型：先检查是否已装箱为正确类型，否则用 Convert
        if (param.IsValueType)
        {
            var convertMethod = GetConvertMethod(targetType);
            if (!string.IsNullOrEmpty(convertMethod))
            {
                return $"{varName} is {targetType} {varName}_v ? {varName}_v : {convertMethod}({varName})";
            }
            // 未知值类型，使用 ChangeType 并传入 typeof
            return $"{varName} is {targetType} {varName}_v ? {varName}_v : ({targetType})System.Convert.ChangeType({varName}, typeof({targetType}))";
        }

        // 引用类型：直接 as 转换
        return $"{varName} as {targetType}";
    }

    private static string GetConvertMethod(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => "Convert.ToInt32",
            "long" or "System.Int64" => "Convert.ToInt64",
            "short" or "System.Int16" => "Convert.ToInt16",
            "byte" or "System.Byte" => "Convert.ToByte",
            "float" or "System.Single" => "Convert.ToSingle",
            "double" or "System.Double" => "Convert.ToDouble",
            "decimal" or "System.Decimal" => "Convert.ToDecimal",
            "bool" or "System.Boolean" => "Convert.ToBoolean",
            "char" or "System.Char" => "Convert.ToChar",
            "uint" or "System.UInt32" => "Convert.ToUInt32",
            "ulong" or "System.UInt64" => "Convert.ToUInt64",
            "ushort" or "System.UInt16" => "Convert.ToUInt16",
            "sbyte" or "System.SByte" => "Convert.ToSByte",
            "DateTime" or "System.DateTime" => "Convert.ToDateTime",
            _ => "" // fallback: 使用 ChangeType
        };
    }

    private static string GetHelperMethodName(ToolMethodModel tool)
    {
        // 用类名和方法名组合，避免特殊字符
        var typeName = tool.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        var methodName = tool.MethodName;
        return $"Call_{typeName}_{methodName}";
    }
}
