using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 为包含 [AiTool] 方法的类型生成 partial 类，包含 AIFunctionDeclaration 静态成员
/// </summary>
public static class ToolDeclarationEmitter
{
    public static string Emit(string namespaceName, string typeName, List<ToolDeclarationModel> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // 处理嵌套类型：如果 typeName 包含 '.'，需要包裹在外层类中
        var parts = typeName.Split('.');
        if (parts.Length > 1)
        {
            for (var i = 0; i < parts.Length - 1; i++)
            {
                sb.AppendLine($"{new string(' ', i * 4)}partial class {parts[i]}");
                sb.AppendLine($"{new string(' ', i * 4)}{{");
            }
            sb.AppendLine($"{new string(' ', (parts.Length - 1) * 4)}partial class {parts[parts.Length - 1]}");
            sb.AppendLine($"{new string(' ', (parts.Length - 1) * 4)}{{");
        }
        else
        {
            sb.AppendLine($"partial class {typeName}");
            sb.AppendLine("{");
        }

        var indent = new string(' ', parts.Length * 4);

        // 为每个方法生成声明
        foreach (var tool in tools)
        {
            var fieldName = $"{tool.MethodName}_ToolDecl";
            var jsonSchema = BuildParametersJsonSchema(tool);
            var returnSchema = BuildReturnJsonSchema(tool);

            sb.AppendLine();
            sb.AppendLine($"{indent}    public static readonly global::ManInBlack.AI.Tools.ToolFunctionDeclaration {fieldName} = new(");
            sb.AppendLine($"{indent}        \"{EscapeString(tool.ToolName)}\",");
            sb.AppendLine($"{indent}        \"{EscapeString(tool.Summary ?? "")}\",");

            // JSON schema 作为 verbatim 字符串
            sb.AppendLine($"{indent}        @\"{EscapeVerbatimString(jsonSchema)}\",");

            if (returnSchema is not null)
                sb.AppendLine($"{indent}        @\"{EscapeVerbatimString(returnSchema)}\"");
            else
                sb.AppendLine($"{indent}        null");

            sb.AppendLine($"{indent}    );");
        }

        // 生成静态数组
        sb.AppendLine();
        sb.AppendLine($"{indent}    public static readonly global::Microsoft.Extensions.AI.AIFunctionDeclaration[] AllToolDeclarations =");
        sb.AppendLine($"{indent}    {{");

        foreach (var tool in tools)
        {
            sb.AppendLine($"{indent}        {tool.MethodName}_ToolDecl,");
        }

        sb.AppendLine($"{indent}    }};");

        // 关闭类和嵌套类型
        if (parts.Length > 1)
        {
            for (var i = parts.Length - 1; i >= 0; i--)
            {
                sb.AppendLine($"{new string(' ', i * 4)}}}");
            }
        }
        else
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 构建参数的 JSON Schema（手动拼接 JSON 字符串）
    /// </summary>
    private static string BuildParametersJsonSchema(ToolDeclarationModel tool)
    {
        var sb = new StringBuilder();
        sb.Append("{\"type\":\"object\",\"properties\":{");

        var firstProp = true;
        foreach (var param in tool.Parameters)
        {
            if (!firstProp) sb.Append(',');
            firstProp = false;

            sb.Append($"\"{EscapeJsonString(param.Name)}\":");
            sb.Append(BuildTypeSchemaJson(param.Type, param.IsNullable,
                tool.ParamDescriptions.TryGetValue(param.Name, out var desc) ? desc : null));
        }

        sb.Append("}");

        // required 数组
        var requiredParams = tool.Parameters
            .Where(p => !p.IsNullable && !p.HasDefaultValue)
            .Select(p => p.Name)
            .ToList();

        if (requiredParams.Count > 0)
        {
            sb.Append(",\"required\":[");
            for (var i = 0; i < requiredParams.Count; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append($"\"{EscapeJsonString(requiredParams[i])}\"");
            }
            sb.Append(']');
        }

        sb.Append('}');
        return sb.ToString();
    }

    /// <summary>
    /// 构建返回值的 JSON Schema
    /// </summary>
    private static string? BuildReturnJsonSchema(ToolDeclarationModel tool)
    {
        if (tool.ReturnsVoid)
            return null;

        return BuildTypeSchemaJson(tool.ReturnType, false, tool.ReturnsDescription);
    }

    /// <summary>
    /// 构建 JSON Schema 类型描述片段
    /// </summary>
    private static string BuildTypeSchemaJson(string type, bool isNullable, string? description)
    {
        var jsonType = MapToJsonSchemaType(type);
        var format = GetFormat(type);

        var sb = new StringBuilder();
        sb.Append('{');

        // type
        if (isNullable)
            sb.Append($"\"type\":[\"{jsonType}\",\"null\"]");
        else
            sb.Append($"\"type\":\"{jsonType}\"");

        // format
        if (format is not null)
            sb.Append($",\"format\":\"{format}\"");

        // description
        if (!string.IsNullOrWhiteSpace(description))
            sb.Append($",\"description\":\"{EscapeJsonString(description!)}\"");

        sb.Append('}');
        return sb.ToString();
    }

    private static string MapToJsonSchemaType(string type)
    {
        switch (type)
        {
            case "int":
            case "System.Int32":
            case "long":
            case "System.Int64":
            case "short":
            case "System.Int16":
            case "byte":
            case "System.Byte":
            case "sbyte":
            case "System.SByte":
            case "uint":
            case "System.UInt32":
            case "ulong":
            case "System.UInt64":
            case "ushort":
            case "System.UInt16":
                return "integer";
            case "float":
            case "System.Single":
            case "double":
            case "System.Double":
            case "decimal":
            case "System.Decimal":
                return "number";
            case "string":
            case "System.String":
            case "char":
            case "System.Char":
            case "System.DateTime":
            case "DateTime":
            case "System.DateTimeOffset":
            case "DateTimeOffset":
                return "string";
            case "bool":
            case "System.Boolean":
                return "boolean";
            default:
                return "object";
        }
    }

    private static string GetFormat(string type)
    {
        switch (type)
        {
            case "System.DateTime":
            case "DateTime":
            case "System.DateTimeOffset":
            case "DateTimeOffset":
                return "date-time";
            default:
                return null!;
        }
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }

    private static string EscapeJsonString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }

    private static string EscapeVerbatimString(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
