using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ManInBlack.AI.SourceGenerator;

/// <summary>
/// 生成 ToolCaller 类的源码
/// </summary>
public static class ToolCallerEmitter
{
    public static string Emit(string namespaceName, List<ToolMethodModel> tools)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1998");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ManInBlack.AI.Tools;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("public class ToolCaller");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public ToolCaller(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CallTool 方法
        EmitCallToolMethod(sb, tools);
        sb.AppendLine();

        // 每个 tool 方法的辅助方法
        foreach (var tool in tools)
        {
            EmitToolHelperMethod(sb, tool);
            sb.AppendLine();
        }

        // 移除最后一个多余空行
        if (sb.Length >= 2 && sb[sb.Length - 1] == '\n' && sb[sb.Length - 2] == '\n')
            sb.Length--;

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitCallToolMethod(StringBuilder sb, List<ToolMethodModel> tools)
    {
        sb.AppendLine("    public async Task CallTool(ToolExecuteContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (context.ToolName)");
        sb.AppendLine("        {");

        foreach (var tool in tools)
        {
            var helperName = GetHelperMethodName(tool);
            sb.AppendLine($"            case \"{tool.ToolName}\":");
            sb.AppendLine($"                await {helperName}(context);");
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new ArgumentException($\"Unknown tool: '{context.ToolName}'.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitToolHelperMethod(StringBuilder sb, ToolMethodModel tool)
    {
        var helperName = GetHelperMethodName(tool);
        sb.AppendLine($"    private async Task {helperName}(ToolExecuteContext context)");
        sb.AppendLine("    {");

        if (tool.FilterTypes.Count > 0)
        {
            EmitFilterPipeline(sb, tool);
        }
        else
        {
            EmitCoreInvocation(sb, tool, "context", "        ");
        }

        sb.AppendLine("    }");
    }

    private static void EmitFilterPipeline(StringBuilder sb, ToolMethodModel tool)
    {
        var indent = "        ";

        // 声明 filter 变量，从 DI 获取或 new
        for (var i = 0; i < tool.FilterTypes.Count; i++)
        {
            var filterType = tool.FilterTypes[i];
            sb.AppendLine($"{indent}var f{i} = ({filterType})_serviceProvider.GetRequiredService(typeof({filterType}));");
        }

        sb.AppendLine();

        // 核心调用作为最内层委托
        sb.AppendLine($"{indent}System.Func<ManInBlack.AI.Tools.ToolExecuteContext, System.Threading.Tasks.Task> next = async ctx =>");
        sb.AppendLine($"{indent}{{");
        EmitCoreInvocation(sb, tool, "ctx", indent + "    ");
        sb.AppendLine($"{indent}}};");

        // 反向包裹 filter（从后往前）
        for (var i = tool.FilterTypes.Count - 1; i >= 0; i--)
        {
            sb.AppendLine($"{indent}var prev{i} = next;");
            sb.AppendLine($"{indent}next = c => f{i}.ExecuteAsync(c, prev{i});");
        }

        sb.AppendLine($"{indent}await next(context);");
    }

    private static void EmitCoreInvocation(StringBuilder sb, ToolMethodModel tool, string ctxVar, string indent)
    {
        // 参数解析
        foreach (var param in tool.Parameters)
        {
            EmitParameterExtraction(sb, param, tool.ToolName, ctxVar, indent);
        }

        // 从 IServiceProvider 获取实例（非静态方法）
        if (!tool.IsStatic)
        {
            sb.AppendLine($"{indent}var instance = (_serviceProvider.GetService(typeof({tool.ContainingTypeName})) as {tool.ContainingTypeName})");
            sb.AppendLine($"{indent}    ?? throw new InvalidOperationException(\"Failed to resolve type '{tool.ContainingTypeShortName}' from IServiceProvider.\");");
        }

        // 调用方法并设置 Result
        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        if (tool.IsStatic)
        {
            if (tool.ReturnsVoid)
            {
                sb.AppendLine($"{indent}{tool.ContainingTypeName}.{tool.MethodName}({argsList});");
                sb.AppendLine($"{indent}{ctxVar}.Result = null;");
            }
            else
            {
                sb.AppendLine($"{indent}{ctxVar}.Result = {tool.ContainingTypeName}.{tool.MethodName}({argsList});");
            }
        }
        else
        {
            if (tool.ReturnsVoid)
            {
                sb.AppendLine($"{indent}instance.{tool.MethodName}({argsList});");
                sb.AppendLine($"{indent}{ctxVar}.Result = null;");
            }
            else
            {
                sb.AppendLine($"{indent}{ctxVar}.Result = instance.{tool.MethodName}({argsList});");
            }
        }
    }

    private static void EmitParameterExtraction(StringBuilder sb, ToolParameterModel param, string toolName, string ctxVar, string indent)
    {
        var varName = $"{param.Name}_raw";
        var targetName = param.Name;
        var targetType = param.Type;

        if (param.HasDefaultValue)
        {
            if (param.IsNullable)
            {
                sb.AppendLine($"{indent}var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
                sb.AppendLine($"{indent}    ? {ConvertExpr(varName, targetType, param)}");
                sb.AppendLine($"{indent}    : {param.DefaultValueExpr};");
            }
            else
            {
                sb.AppendLine($"{indent}var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
                sb.AppendLine($"{indent}    ? {ConvertExpr(varName, targetType, param)}");
                sb.AppendLine($"{indent}    : {param.DefaultValueExpr};");
            }
        }
        else if (param.IsNullable)
        {
            sb.AppendLine($"{indent}var {targetName} = {ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) && {varName} is not null");
            sb.AppendLine($"{indent}    ? {ConvertExpr(varName, targetType, param)}");
            sb.AppendLine($"{indent}    : null;");
        }
        else
        {
            sb.AppendLine($"{indent}if (!{ctxVar}.Arguments.TryGetValue(\"{param.Name}\", out var {varName}) || {varName} is null)");
            sb.AppendLine($"{indent}    throw new ArgumentNullException(\"{param.Name}\", \"Required non-nullable parameter '{param.Name}' is missing or null for tool '{toolName}'.\");");
            sb.AppendLine($"{indent}var {targetName} = {ConvertExpr(varName, targetType, param)};");
        }
    }

    /// <summary>
    /// 生成类型转换表达式（所有类型名使用全称）
    /// </summary>
    private static string ConvertExpr(string varName, string targetType, ToolParameterModel param)
    {
        // string 类型直接 as 转换
        if (targetType == "string" || targetType == "System.String")
            return $"{varName} as string ?? {varName}?.ToString()";

        // bool 特殊处理
        if (targetType == "bool" || targetType == "System.Boolean")
            return $"{varName} is bool {varName}_b ? {varName}_b : Convert.ToBoolean({varName})";

        // 常见值类型：先检查是否已装箱为正确类型，否则用 Convert
        if (param.IsValueType)
        {
            var convertMethod = GetConvertMethod(targetType);
            if (!string.IsNullOrEmpty(convertMethod))
            {
                return $"{varName} is {targetType} {varName}_v ? {varName}_v : {convertMethod}({varName})";
            }
            // 未知值类型，使用 ChangeType 并传入 typeof
            return $"{varName} is {targetType} {varName}_v ? {varName}_v : ({targetType})System.Convert.ChangeType({varName}, typeof({targetType}))";
        }

        // 引用类型：直接 as 转换
        return $"{varName} as {targetType}";
    }

    private static string GetConvertMethod(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => "Convert.ToInt32",
            "long" or "System.Int64" => "Convert.ToInt64",
            "short" or "System.Int16" => "Convert.ToInt16",
            "byte" or "System.Byte" => "Convert.ToByte",
            "float" or "System.Single" => "Convert.ToSingle",
            "double" or "System.Double" => "Convert.ToDouble",
            "decimal" or "System.Decimal" => "Convert.ToDecimal",
            "bool" or "System.Boolean" => "Convert.ToBoolean",
            "char" or "System.Char" => "Convert.ToChar",
            "uint" or "System.UInt32" => "Convert.ToUInt32",
            "ulong" or "System.UInt64" => "Convert.ToUInt64",
            "ushort" or "System.UInt16" => "Convert.ToUInt16",
            "sbyte" or "System.SByte" => "Convert.ToSByte",
            "DateTime" or "System.DateTime" => "Convert.ToDateTime",
            _ => "" // fallback: 使用 ChangeType
        };
    }

    private static string GetHelperMethodName(ToolMethodModel tool)
    {
        // 用类名和方法名组合，避免特殊字符
        var typeName = tool.ContainingTypeName.Replace("<", "_").Replace(">", "_").Replace(".", "_");
        var methodName = tool.MethodName;
        return $"Call_{typeName}_{methodName}";
    }
}
