services:
  feishu-adaptor:
    build:
      context: ..
      dockerfile: demo/FeishuAdaptor/Dockerfile
    ports:
      - "5249:8080"
    env_file:
      - FeishuAdaptor/.env
    environment:
      - SKIP_SSL=true